version: '3'

services:
  redis:
    container_name: 1fps_redis
    image: redis:latest
    command: redis-server --protected-mode no
    ports:
      - "127.0.0.1:8877:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
